
library(whisker) # logicless templating system

template <- "

# R code generated by BayesXShinyApp
# on: {{on}}
# user: {{user}}

library(BayesXShinyApp)

output <- bayesXOutput('{{prg_path}}')

# defautl grid of covariates
variables <- variables(output)
X <- expand.grid(sapply(variables, function(var){
                          seq(0, 1, length.out = 101)
                        }, simplify = FALSE, USE.NAMES = TRUE))

params <- parameters(output, X) # calc parameter samples on default grid

{{Rcode}}

"

create_RScript <- function(tmpl = template,
                           on = Sys.time(),
                           user = Sys.info()[["user"]],
                           prg_path,
                           Rcode){
  
  rscript <- whisker.render(tmpl, list(prg_path = prg_path,
                                     on = on, 
                                     user = user,
                                     Rcode = Rcode))
  
  return( rscript )
}



