
library(whisker) # logicless templating system

template <- "

# R code generated by BayesXShinyApp
# on: {{on}}
# user: {{user}}

library(BayesXShinyApp)

output <- BayesXShinyApp:::bayesXOutput.character('{{prg_path}}')

{{Rcode}}

"

create_RScript <- function(tmpl = template,
                           on = Sys.time(),
                           user = Sys.info()[["user"]],
                           prg_path,
                           Rcode){
  
  rscript <- whisker.render(tmpl, list(prg_path = prg_path,
                                     on = on, 
                                     user = user,
                                     Rcode = Rcode))
  
  return( rscript )
}



