% usefile /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_samples.prg

dataset _d
graph _g

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_LinearEffects_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_LinearEffects_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_spatial_MRF_effect_of_distH9_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_spatial_MRF_effect_of_distH9_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH9_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH9_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_rho_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_LinearEffects_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_LinearEffects_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_spatial_MRF_effect_of_distH7_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_spatial_MRF_effect_of_distH7_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_spatial_MRF_effect_of_distH7_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_spatial_MRF_effect_of_distH7_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_LinearEffects_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_LinearEffects_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_spatial_MRF_effect_of_distH5_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_spatial_MRF_effect_of_distH5_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH5_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH5_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_sigma_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_LinearEffects_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_LinearEffects_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_edupartner_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_nonlinear_pspline_effect_of_edupartner_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_edupartner_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_nonlinear_pspline_effect_of_edupartner_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_spatial_MRF_effect_of_distH3_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_spatial_MRF_effect_of_distH3_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_spatial_MRF_effect_of_distH3_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_wasting2_variance_of_spatial_MRF_effect_of_distH3_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_LinearEffects_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_LinearEffects_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_cage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_breastfeeding_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mbmi_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_mage_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_medu_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_medu_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_edupartner_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_nonlinear_pspline_effect_of_edupartner_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_edupartner_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_nonlinear_pspline_effect_of_edupartner_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_spatial_MRF_effect_of_distH_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_spatial_MRF_effect_of_distH_sample.ps using _d

_d.infile using /Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH_sample.raw
_g.plotsample , outfile=/Users/aleksandarspasojevic/Desktop/template_bivariate/results/NV_s1_di_ca_me_mb_br_ma_s2_di_ca_mb_br_rho_ca_di_ma_br_MAIN_mu_REGRESSION_stunting2_variance_of_spatial_MRF_effect_of_distH_sample.ps using _d

drop _d _g

