#' extracts key value pairs from 'output' directory generated by bayesX CLI
#' @note we do not export this method, is an internal method
get_key_values <- function(line, data_env, ...){
  key_values <- unlist(strsplit(line, ","))
  meta <- list()
  for (pair in key_values) {
    splitted <- unlist(strsplit(pair, "="))
    key <- splitted[1]; value <- splitted[2]
    meta[key] <- value
  }
  # if line contains 'term' we declare it as an effect
  is_effect <- grepl("term", line)
  if ( is_effect )
    class(meta) <- c("effect", class(meta))
  
  return(meta)
}


#' 'bayesXOutput' constructor for 'output/' files generated by bayesX CLI
#'
#' class which contains information about 'output/' files generated by
#' \code{\link{bayesX}}
#'
#' @param bayesXResult is the object generated by \code{\link{bayesX}}
#'
#' @export
bayesXOutput <- function(bayesXResult, ...) UseMethod("bayesXOutput")

#' @export
bayesXOutput.bayesXResult <- function(bayesXResult, ...){
  r_file <- readLines(list.files(output_path(bayesXResult), "*.r$",
                                 full.names = TRUE))
  # extract information of .r file in output per line
  output_meta <- lapply(r_file, get_key_values, attr(bayesXResult, "data_env"))
  class(output_meta) <- c("bayesXOutput", class(output_meta))
  attr(output_meta, "data_env") <- attr(bayesXResult, "data_env")
  return(output_meta)
}


#' @note since user only passes the output directory, we do not know where
#' data sample is stored
#' 
#' @rdname bayesXOutput
#' 
#' @export
bayesXOutput.character <- function(path, ...){
  r_file <- readLines(list.files(path, "*.r$", full.names = TRUE))
  # extract information of .r file in output per line
  output_meta <- lapply(r_file, get_key_values, NULL)
  class(output_meta) <- c("bayesXOutput", class(output_meta))
  attr(output_meta, "data_env") <- NULL
  return(output_meta)
}


#' subscript operator for 'bayesXOutput' objects
#'
#' extracts meta information out of 'output/*.r' file generated by
#' \code{\link{bayesX}}
#'
#' @param bayesXOutput is the object generated by \code{\link{bayesXOutput}}
#'
#' @export
"[.bayesXOutput" <- function(bayesXOutput, i, drop = TRUE, ...){
  sapply(bayesXOutput, "[", i, drop = drop, ...)
}


#' @export
variables.bayesXOutput <- function(bayesXOutput, ...){
  variables <- lapply(bayesXOutput, function(elem){
    tryCatch(variables(elem), 
             warning = function(w) NULL, 
             error = function(e) NULL)
  }, ...)
  return( unique(unlist(variables)) )
}

